CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(250) NOT NULL UNIQUE,
    password VARCHAR(250) NOT NULL
);

CREATE TABLE todos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    users_id INT NOT NULL,
    content VARCHAR(100),
    due DATETIME,
    FOREIGN KEY (users_id) REFERENCES users(id)
);

CREATE TABLE frage_1(
    id INT AUTO_INCREMENT PRIMARY KEY,
    namen VARCHAR(100) NOT NULL,
);

CREATE TABLE frage_2(
    id INT AUTo_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOZ NULL,
);

CREATE TABLE frage_3(
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
);

CREATE TABLE frage_4(
    id INT AUTO_INCREMENT PRIMARY KEY,
    tierart VARCHAR(100) NOT NULL,
);

CREATE TABLE frage_5(
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
);

CREATE TABLE frage_6(
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    
);

